# Site settings
title: Casburn Noronha
description: 'This is my journey into the world of IT.'
url: 'https://casburn1988.github.io'
baseurl: '/'
google_analytics: 'UA-61560423-1'
disqus_shortname: 'slaaygithubio'

author:
  name: 'Casburn Noronha'
  email: casburn.noronha@gmail.com
  twitter_username: slaaysrcecoders
  facebook_username: slaaysourcecoders
  github_username:  casburn1988
  linkedin_username:  casburnnoronha

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
